### ISSUE TITLE
Produces/consumes is not defined in OA3

### ISSUE THREAD

**Issue by ghost** [acr-lfr/generate-it-typescript-server#137]
Produces is not defined in OA3, instead it's written in requestBody->content->"application/json" (consumes) and responses->code->content->"application/json" (produces).

Therefore this src/http/nodegen/routes/___op.ts.njk line 39 and the "inferResponseType" should be changed.

**Comment by p-mcgowan** [comment]
the inferResponseType thing needs to be re-written or refactored heavily - there are a few issues with it.

The first mistake was building for OA2 first, then shimming in OA3 after, but I believe [this issue)[https://github.com/acrontum/generate-it-typescript-server/issues/96] addresses this (this one can be closed if it is in fact a duplicate).

With v6 in the works, it might be worth dealing with it then, but PR's welcome :)

**Comment by SergiAcrontum** [comment]
Alright. For now `x-passResponse: true` does the trick. I guess we can figure out a better way for v6.

**Comment by johndcarmichael** [comment]
@p-mcgowan  the infer and the routes file are 2 different issues

The routes file tpl needs to look for the produces attribute and if not found needs a way to extract the produces from the OA3 format.

**Comment by p-mcgowan** [comment]
Ah yes ok, I misunderstood - I read the inferResponseType first and ignored the rest of the question...

Yeah, if the pass-response works then it's not a complete blocker - I'll re-open it though since it's good to keep it in view and if it's related to another fix then they might both get closed in 1 shot

**Comment by j-d-carmichael** [comment]
this has now been resolved on the latest PR
