### ISSUE TITLE
npm celebrate is falling behind 

### ISSUE THREAD

**Issue by j-d-carmichael** [acr-lfr/generate-it-typescript-server#155]
https://www.npmjs.com/package/celebrate

This tpl is on version 12.. but the latest is now on 15. We should upgrade asap to keep up

**Comment by j-d-carmichael** [comment]
bump

@p-mcgowan  we already had an issue here after all

**Comment by p-mcgowan** [comment]
sounds about right... will toss it on the todo pile

**Comment by j-d-carmichael** [comment]
I thought i could do this one in a quick 15min job - doesn't look to be that simple

**Comment by p-mcgowan** [comment]
Yeah, I think I took a whack at it ages ago and it's mostly just interface changes but there are some functional changes... It's still on my todo list...

**Comment by j-d-carmichael** [comment]
cool - i will leave that one to you then an I will try and find a minute to migrate to eslint from tslint on the core
