### ISSUE TITLE
Typo on plural models

### ISSUE THREAD

**Issue by acrontum-sanchez** [acr-lfr/generate-it-typescript-server#167]
When the model ends with an "s" or a "y" the generated models name is wrong.

Example:
For an Address model I need to use "Addresss" if I want to return more than 1 address.
Same for Study model. I need to use "Studys"  instead of Studies. 

Would be great to add this exceptions to have nice models names in the code.

Everything that ends with an "s" the plural shoul be generated as "es" Address -> Addresses, 
and everything ending with "y" should be generated as "ies" replacing the "y". Study -> Studies.

**Comment by acrontum-sanchez** [comment]
Response example:

responses:
  '200':
    description: Successful request
    content: {{ mixin("../../mixins/response/json.yml", "#/components/schemas/Address**S**") }}

**Comment by p-mcgowan** [comment]
@zewish 
is this closed in https://github.com/liffery-com/boats/pull/52 or is this unrelated?
