### ISSUE TITLE
Add option to pass domain params as object instead of positional

### ISSUE THREAD

**Issue by p-mcgowan** [acr-lfr/generate-it-typescript-server#169]
eg for supporting decorators

Would be useful to have an option to use an object in the domain files instead of positional arguments - then you can always rely on the same test for args.

for instance:

```typescript
async getThings(body: Body, query: Query) {}

async getOtherThings(query: Query) {}
```
means query is not always in the first position.

however, optionally allowing a nodegenReq object would solve this

```typescript

async getThings(nodegenParams: { body?: Body; query?: Query, request?: NodegenRequest }) {}

// params.query is always the same access
async getOtherThings(nodegenParams: { body?: Body; query?: Query, request?: NodegenRequest }) {}
```

**Comment by j-d-carmichael** [comment]
agreed - however this would be an option like this would have to come from the core not the tpl

**Comment by j-d-carmichael** [comment]
i you agree could we close/move this one?

**Comment by p-mcgowan** [comment]
I would think this would be exclusive to the template, right? As it only pertains to the express controller params, I think it makes the most sense inside there?

I think it's fairly straightforward as well - there could be a config option in nodegen config (which wouldn't required modifying the core at all, or even a separate config if necessary), and in [routes/__op:38](https://github.com/acr-lfr/generate-it-typescript-server/blob/master/src/http/nodegen/routes/___op.ts.njk#L38) we could just wrap the params in an object?

something like:
```
await {{ucFirst(operation_name)}}Domain.{{path.operationId}}({{tsExpressHelperDomainWrapper(method, path, false, true, 'params')}}){% if not path['x-passResponse'] -%},{% endif %}
```
and a helper file in the tpl which calls the `pathParamsToDomainParams` but wraps the output?

not sure - i mean it's prolly easier to toss it in the core but would love to see less template-specific logic creeping into the core

**Comment by j-d-carmichael** [comment]
Would be a bit of both i reckon - the core function pathParamsToDomainParams would be easier to handle if it output an object 

I don't like the idea of writing logic into the templates, even though the helpers is a thing.. tpls. As an object output you can then use tpl syntax.. set the output to a variable, the add the variable as required in the tpl.

**Comment by p-mcgowan** [comment]
True, I mean either works. I thought the idea was generally to decouple the core from template implementation, but I don't see that happening soon.

I'm on board to move it into the core - definitely would be easier. I do love the idea of helpers / env.globals in the templates though but that's a whole 'nother beast

**Comment by j-d-carmichael** [comment]
As is it already in the core - a nicer stepping stone will be if you pass the 1st arg as an object of options for the helper.

Then you can control how you want the data from the core, as a string  or object for the tpl to place how it wants. This improves the options for all tpls and not just this one.

Then if the desire is still there to change how the args are passed to the domain in this tpl it can be done much easier - that being said, this level of a change is quite big and will disrupt many existing apis

**Comment by p-mcgowan** [comment]
Yeah sounds good. I'm not personally using it but might make passing domain args to services a bit easier - that being said, we might lose some typings if we loosen it up to all optional, but would have to dig in

**Comment by j-d-carmichael** [comment]
This for the core, and would be called from the tpl. "path params to domain params"
