### ISSUE TITLE
Cannot update to TypeScript v4.5.x due to zerollup issue 

### ISSUE THREAD

**Issue by j-d-carmichael** [acr-lfr/generate-it-typescript-server#194]
4.5.x results in a ts build error:
```
TypeError: Cannot read property 'impliedNodeFormat' of undefined
```

The issue is narrowed down to this:
https://github.com/zerkalica/zerollup/issues/37

There is a PR on it, but it is not being merged in by the maintainer:
https://github.com/zerkalica/zerollup/pull/38

The PR didn't appear to work after a few attempts of tsconfig and package json configs.

The package.json has pegged ts to ~4.3.5 for now until the fix is out

**Comment by p-mcgowan** [comment]
https://github.com/zerkalica/zerollup/issues/37#issuecomment-984860540 resolves it by just patching zerollup after install

**Comment by p-mcgowan** [comment]
would definitely just look into ts-config-paths more heavily. seems like a solid option and has a lot of usage, very common in other projects.

**Comment by j-d-carmichael** [comment]
this has been resolved a long time ago
