### ISSUE TITLE
tsc-alias not really working

### ISSUE THREAD

**Issue by acrontum-sanchez** [acr-lfr/generate-it-typescript-server#223]
Since the last changes, I can not run locally  `npm run dev:build-watch` and `dev:start-watch`. 
I get the following error using it on a project from scratch:

```
Error: Cannot find module '@/http'
Require stack:
- /code/playground/gen/build/src/app.js
- /code/playground/gen/build/server.js
```
This was working fine before the change of ts-watch.

Also, I don't understand the docker-entrypoint.sh watch since it just call  `npm run dev:build-watch`. Probably this is there for a long time and nobody is using it like in the template because it does not work like this and in the docker-compose still uses ts-watch.

Would be nice to know how the docker-compose and docker-entrypoint are modified by different teams to be able to use them.

**Comment by j-d-carmichael** [comment]
@acrontum-sanchez  is this working now with yours and @p-mcgowan  PR - can this issue be closed?

**Comment by p-mcgowan** [comment]
Yep, I think this was the driver behind the PR #222.

Let's close it and open another if necessary.
