### ISSUE TITLE
Rename suggestion

### ISSUE THREAD

**Issue by Acrontum-Carmichael** [acr-lfr/generate-it-typescript-server#95]
**generate-it-typescript-server** is descriptive but could be snappier and improved.
As a suggestion and naming pattern, how about, **generate-it-ts-express** or **gen-ts-express**

**Comment by p-mcgowan** [comment]
yeah I like the shorter naming convention - gen-ts-express (or gen-express-ts) would be easier to type

**Comment by Acrontum-Carmichael** [comment]
Or maybe we just drop "ts" and just don't accept anything in pure js anymore?

**Comment by Acrontum-Carmichael** [comment]
the core could also be renamed to gen-it too as is currently not taken on npm

**Comment by p-mcgowan** [comment]
Yeah I think those would work - `gen-it` and `gen-it-express`. Would make my folder structure shorter
